#!/bin/bash -l
#SBATCH -p debug 
####SBATCH -A stsda
#SBATCH -J "ecxmu_4" 
#SBATCH --time=02:00:00
#SBATCH -o Err_Out/%j.out 
#SBATCH -e Err_Out/%j.err
#SBATCH -n 1 
#SBATCH -c 1 

module load r/3.4.2
echo "2 $SLURM_JOBID `date`" | tee -a ~/EVAChallenge2019/IBEXcluster/Runtime_eCDF_excmu.txt

OMP_NUM_THREADS=1 Rscript /home/castroda/EVAChallenge2019/IBEXcluster/JobsAllLoc/GetExpUnifGaussData_excmu_4.R 

echo "2 $SLURM_JOBID `date`" | tee -a ~/EVAChallenge2019/IBEXcluster/Runtime_eCDF_excmu.txt
